git_repository(
    name   = "com_github_gflags_gflags",
    tag = "v2.2.0",
    remote = "https://github.com/gflags/gflags.git",
)

bind(
    name = "gflags",
    actual = "@com_github_gflags_gflags//:gflags",
)
