package(default_visibility = ["//visibility:public"])

py_binary(
		name = "generate_dataset",
		srcs = ["generate_dataset.py"],
)

py_binary(
		name = "evaluate_norm",
		srcs = ["evaluate_norm.py"],
)
