javac -sourcepath .;.. AM.java
javac -sourcepath .;.. AMInfo.java
javac -sourcepath .;.. channel.java
javac -sourcepath .;.. Const.java
javac -sourcepath .;.. Executor.java
javac -sourcepath .;.. HostInfo.java
javac -sourcepath .;.. JarClassLoader.java
javac -sourcepath .;.. PerformFunction.java
javac -sourcepath .;.. point.java
javac -sourcepath .;.. ServerQuery.java
javac -sourcepath .;.. task.java
javac -sourcepath .;.. UDPQuery.java
javac -sourcepath .;.. EventTrace.java
javac -sourcepath .;.. IRecovery.java
javac -sourcepath .;.. Recover.java
javac -sourcepath .;.. RecoveryFactory.java
javac -sourcepath .;.. SafeRun.java
javac -sourcepath .;.. TieRecoveries.java
