java_test(
    name = "nfa_tests",
    srcs = ["NFATest.java"],
    test_class = "io.github.lionell.lab2.NFATest",
    deps = [
        "//java/io/github/lionell/lab2:nfa",
        "//third_party:guava",
        "//third_party:junit4",
        "//third_party:truth",
    ],
)
