java_test(
    name = "cpp_tests",
    srcs = ["CppTest.java"],
    test_class = "io.github.lionell.lab3.CppTest",
    deps = [
        "//third_party:guava",
        "//third_party:junit4",
        "//third_party:truth",
    ],
)
