java_test(
    name = "frequency_sorter_tests",
    srcs = ["FrequencySorterTest.java"],
    test_class = "io.github.lionell.lab1.FrequencySorterTest",
    deps = [
        "//java/io/github/lionell/lab1:frequency_sorter",
        "//third_party:guava",
        "//third_party:junit4",
        "//third_party:truth",
    ],
)

java_test(
    name = "cliques_finder_tests",
    srcs = ["CliquesFinderTest.java"],
    test_class = "io.github.lionell.lab1.CliquesFinderTest",
    deps = [
        "//java/io/github/lionell/lab1:cliques_finder",
        "//third_party:guava",
        "//third_party:junit4",
        "//third_party:truth",
    ],
)
